### ISSUE TITLE
A not_analyzed field can't have a "Select Analyzer" option

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/gem#3]
Analyzer options should be available only on analyzed string (or text) fields.

Example of UI currently where this option is available to a `not_analyzed` field.

![](https://i.imgur.com/kLthmjT.png)

**Comment by siddharthlatest** [comment]
Analyzers can only be applied on `string` fields.

The following is also an example of an incorrect analyzer option.

![](https://i.imgur.com/HMP4em7.png)

**Comment by farhan687** [comment]
Allow analyzer for only string and anlyzed field: Fixed over here-  8e1eeb5a5d0ec34293aa1e253cf81de67d68ac8e
